[build]
  # This line confirms where your functions are located
  functions = "netlify/functions"

[[redirects]]
  # This must match the URL in your frontend JS
  from = "/api/chat"
  # This must match the actual function location
  to = "/.netlify/functions/chat"
  # This forces Netlify to handle ALL methods (GET, POST, OPTIONS) as a function call
  status = 200
  force = true